### ISSUE TITLE
Request: Support for PvP

### ISSUE THREAD

**Issue by Loseriana** [Infiziert90/MOActionPlugin#108]
I've been trying my hand at PvP for the mount and really miss this plugin while at it.

I saw that someone requested the same some time ago so I'm not the only one who would appreciate the feature.

**Comment by Alluneve** [comment]
So, PvP is a competitive aspect of this game, and in my opinion, it should not receive any QOL/changes from any plugins.
because it conceptually breaks the balance of anyone using/not using a plugin.

but technically all that is stopping it from working with any ability in the game is some validation checks on loading your saved configuration and on load, reading in all existing job actions from the excel sheet inside Lumina.

Doing so would mix pvp and non-pvp in the configuration/UI, which is another mess I would like to avoid.
IF these features were considered, I would have it exist in functional UI in a separate Tab, split away from existing stacks.

So functionally not that big of a deal to do, but would require new UI bits, 
on the other hand, I'm unconvinced to do it, as as soon as you are talking player versus player environments, what is fair, balanced, ... for all parties involved is brought into question.

**Comment by Loseriana** [comment]
That's a fair point, I guess. I was only playing daily for the mount, but i understand that any change would unbalance things to my side in a more competitive mode.

**Comment by Infiziert90** [comment]
This wouldn't be allowed by the plugin guidelines, as Alluneve already said that PvP would be a fair advantage for one side, so closing this as not possible
