### ISSUE TITLE
Role Abilities only work for 1 job

### ISSUE THREAD

**Issue by Noshei** [Infiziert90/MOActionPlugin#33]
If you setup a Role ability as the base action it will only work for 1 class.  To give specifics of how I am running into this issue, I have Esuna setup for both SCH and WHM with Esuna on UI and Field Mouseover and then a damage ability on Target.  Currently the damage ability will only work for WHM, I get an error on SCH saying I can't use that ability on that job.

**Comment by pigsflew** [comment]
It'd be really nice to have it actually work oppositely to how it does now: Set up an action config, then map it to *multiple actions*.

I really want all my ground targeted heal bubbles, esuna, raise, etc, to work the same no matter which class I'm in.

I want Raise/Ascend/Egeiro/Resurrection/Verraise to all map to a single stack, whether I'm in WHM/AST/SGE/SCH/SMN/RDM, because they're all *the same skill*.

**Comment by Alluneve** [comment]
This is a duplicate of a closed issue, this had to do with stacks bleeding over (closable)
