### ISSUE TITLE
"Target" target does not work for NPC's

### ISSUE THREAD

**Issue by DenL** [Infiziert90/MOActionPlugin#47]
![image](https://user-images.githubusercontent.com/5632219/140070577-15452a38-b0fd-4631-ac0d-2790422cbe36.png)

Having the stack set up as above, targeting an NPC and casting Cure II would cast the Cure II on self. If the stack is deleted, NPC can be healed normally. It seems stack #5 in above screenshot is not working for NPC's.

**Comment by natyusha** [comment]
NPCs don't work as of yet and I'm not sure if it is planned or not.

https://github.com/attickdoor/MOActionPlugin/issues/16

**Comment by chrono414** [comment]
I'm not sure if attickdoor is still looking at it - I am also facing this issue as a healer in the MSQ. I'm not at all familiar with the Dalamud plugin, but I spent about half an hour to look through the code, and I'm wondering if it's possible that friendly battleNPCs are not of the BattleNpc type at all? I see in the Dalamud documentation that BattleNpcSubKind only contains Chocobo, Enemy, None, and Pet. ([Dalamud doc](https://goatcorp.github.io/Dalamud/api/Dalamud.Game.ClientState.Objects.Enums.BattleNpcSubKind.html))

If the friendly NPC is not of the BattleNpc type then it might make sense since the method CanUseAction in MOAction.cs will then fall through and return false, because none of the other checks check for friendly NPCs.

This is just a conjecture though, I don't really know how to test it out. Would appreciate if attickdoor can look into it and give an answer. I could just disable the plugin during these events, but it'll be perfect if it works for NPCs.
