### ISSUE TITLE
[suggestion] prevent self casting when nothing is on MO

### ISSUE THREAD

**Issue by Khuzvhan** [Infiziert90/MOActionPlugin#7]
As a previous MO Macro User, the only "good" thing about them was this feature.  I love not having to use them anymore but preventing cast if you failed to aim would be awesome.

**Comment by johnysandels** [comment]
I feel like a better option would to be preventing self cast if target is out of range.

**Comment by attickdoor** [comment]
It's not a terrible idea.

**Comment by Khuzvhan** [comment]
Hey! bumping this old suggestion to ask if there's still any interest on implementing this feature.

While preventing casts if the target is out of range was a good suggestion made by John. Let's say you are running an Alliance Raid and wanna throw an emergency Benediction on someone right next to you by field mouseover. If the player makes some quick movement or you don't aim properly you still gonna waste that bene on yourself.  And this is true for most situations even for UI targeting because the party frames work in some bizarre ways sometimes. like if there's an enemy right under your party frames, you cursor aim goes through the frame and become an offensive cursor actually aiming at the enemy and the same wasted casts occurs. 

Thanks for the long time work on this "must-have" tool for some players, specially coming from a decade of healing in other games with better working built in mouseover unlike XIV.

**Comment by johnysandels** [comment]
So you're suggesting a time buffer after losing your target to still use the ability on that target? And I imagine the buffer would have to be quite low so you don't heal a friendly target when you actually tried to heal yourself. 

And second, if you're using a healing spell while over an enemy and a friendly target, it'll default to healing the friendly target instead of healing yourself?

On that note, maybe an option to disable self healing entirely unless you target yourself. For those who only target themselves to heal themselves. (Probably wouldnt fit the scope of this plugin though. Maybe simple tweaks could either have/add it?)

**Comment by Khuzvhan** [comment]
> So you're suggesting a time buffer after losing your target to still use the ability on that target? And I imagine the buffer would have to be quite low so you don't heal a friendly target when you actually tried to heal yourself.
> 
> And second, if you're using a healing spell while over an enemy and a friendly target, it'll default to healing the friendly target instead of healing yourself?
> 
> On that note, maybe an option would be to disable self healing entirely unless you target yourself. For those who only target themselves to heal themselves. (Probably wouldnt fit the scope of this plugin though. Maybe simple tweaks could either have/add it?)

No. My single suggestion is to not Self Cast if you don't meet any stacks requirement.

**Comment by Alluneve** [comment]
closable, was implemented long ago
