### ISSUE TITLE
Phlegma on Sage issue.

### ISSUE THREAD

**Issue by ghost** [Infiziert90/MOActionPlugin#71]
I haven't had any problems with Dosis as the other person listed. I'm having an Issue with Phlegma, and I have tried to be as thorough as possible.
It only seems to work directly on target. 
I have tried all the options UI mousover, Field Mousover, Focus Target, and Target of Target.
None of them work I just get an Invalid Target error. 
These errors also prevent movement in the stack.
I have tried following Phlegma with another offensive spell, like Dosis, as well as a beneficial, Diagnosis.
I have also tried each option while targeting myself, and each option while targeting a 3rd party.
Lastly, I have tried this by setting the plugin to each version of the spell, Phlegma, Phlegma II, and Phlegma III.
Either way, when Phlegma get's the Invalid Target error, the stack does not continue.

[<https://vimeo.com/728571424/728a062fc8>](url)

I don't know why I ran in at the end, force of habit I guess. However you can see in the beginning the Spell's MP value is white and I was in range the whole time. It's 2 on the top left hotbar.

Thank you for your time. In reading this, and in making this wonderful plugin.
I hope this helps! [<a href="https://imgur.com/fnT24Sr"><img src="https://i.imgur.com/fnT24Sr.png" title="source: imgur.com" /></a>](url)

**Comment by auxao** [comment]
Oh! I forgot to mention I also tried all versions of the spell, Phlegma, Phlegma II, and Phlegma III. The results were the same.

**Comment by wirchtalksgames** [comment]
I can add to this by saying that I haven't gotten a single SGE skill to work properly; it's not just Phlegma, though I am also having the same problem as OP. I've tried with Taurochole, Dosis, Diagnosis, Phlegma, Pneuma, and other OGCD skills, and they don't work with any of the action types. Further, neither Eukrasian Dosis nor Diagnosis are available as stackable actions, which kinda defeats the point of the mouseover aspect since we can't refresh DoTs with the same ease as other classes.

One last addition to my report would be that SGE is the only class that doesn't let me delete stacks. I can delete all the stacks I've created for it except for the last one. Whenever I click on "Delete Stack" then, the stack just jitters and stays there, and won't let itself get deleted.

Thanks in advance for the help!

**Comment by wirchtalksgames** [comment]
I figured it out. You need to select "Phlegma" and not "Phlegma I, II, or III" for it to work. Same with Dosis—if you want to apply DoTs on mouseover, you'll want to select "Dosis" and not "Dosis I, II, or III".

**Comment by Grandorg22** [comment]
I have the same Problem as White Mage with Divine Benison and Aqua Veil. But this Problems start appearing after the 6.18 Patch. I already deleted the Stack for it and dragged the Actions on my Actionbars from the Spellbook, but still won't work  with the Plugin.

**Comment by Alluneve** [comment]
old version, was fixed, closable
