### ISSUE TITLE
Target of Target does not fail over

### ISSUE THREAD

**Issue by iFral** [Infiziert90/MOActionPlugin#76]
![image](https://user-images.githubusercontent.com/30185603/192165517-e34e9d0f-36cf-4dc1-aa3c-516c2e841458.png)

In the attached stack, target of target simply fails the cast as an invalid target instead of failing over to casting on the target. I've also tested if adding target to the stack will work and the stack fails with invalid target and does not proceed past target of target to target either. Before the behavior was that if target of target was an invalid target the stack would fail over to normal behavior and attempt to cast on the target.

**Comment by Aqua-1994** [comment]
is this scenario one where a target of target exists, but the target of target was an invalid target for your spell?
example given: you're in an alliance raid and the tank of another party is the main tank on the boss?

because in that scenario, MOActionPlugin sees a target of target exists and sees them as a valid option and hands it off to the game to execute.

this plugin does not think for you, if your stack results in:
"invalid target, because you're trying to cast enkindle on someone outside your party",
then that is what your character attempts to do.
because the target of your action is a **Player** and your action **can target party members**.



_That said, incidentally I'm working on a fix for healable battlenNPCs by delegating more of this functionality to the game instead of doing it myself and this could by proxy be resolved_

**Comment by Alluneve** [comment]
closable, completed
