### ISSUE TITLE
[DRG] Stack Problem

### ISSUE THREAD

**Issue by MadMadaMim** [Infiziert90/MOActionPlugin#86]
So I'm pretty sure this wasn't an issue before but I could very well be wrong. My Dragoon is level 61 and before the update I had a stack of Dragonfire Dive>Geirskogul>Doom Spike and the stack just seemed to ignore the Dive and Geir when I was running content below their respective levels (50 & 60) but now the stack gets locked up and doesn't work at all when those abilities aren't available do to content level. Is this the new normal, am I going crazy, and this was never a thing or is this just a bug? Thanks!

**Comment by Aqua-1994** [comment]
that's not really how this plugin works, this plugin does not skip an action just because you have not learned it yet.

all it does is check if you could use that action and delegate doing the action to the game, it does not concern itself with if you have learned the spell or not. 

you could technically attempt to cast a spell from another class and the plugin won't care, the game would be confused however

**Comment by Alluneve** [comment]
closable, i think implemented
